### ISSUE TITLE
Distance between pins 7 and 8

### ISSUE THREAD

**Issue by cesarab** [FPGAwars/Alhambra-II-FPGA#8]
Hi.

Is there any reason why the distance between GPIO pins 7 and 8 is not multiple of 100 mils (2.54 mm)?

I wanted to create a hat for the FPGA, out of a regular perfboard, but it doesn't fit because of that.

The other side of the board does maintain the correct distance.

![screenshot](https://user-images.githubusercontent.com/3441154/72472432-74cac500-37dc-11ea-92d6-4924a68e6c99.png)

**Comment by cesarab** [comment]
Nevermind. I can see that arduino has the same distance and this card keeps the Arduino form factor, so I gues that's the answer to my question.

**Comment by Obijuan** [comment]
Yes, that is the reason: keeping the board compatible with Arduino Uno. All
the shields for the Arduino Uno can be used with the Alhambra II board
